export const profissionais = [
  {
    id: 1,
    nome: 'Carlos Silva',
    cargo: 'Desenvolvedor Full Stack',
    foto: '/images/carlos-silva.jpg',
    nota: 4.9,
    totalAvaliacoes: 127,
    localizacao: 'Joinvile, SC',
    projetosConcluidos: 256,
    servicos: [
      { titulo: 'Desenvolvimento de Website', precoMin: 3000, precoMax: 8000, prazo: '2-4 semanas' },
      { titulo: 'App Mobile (iOS/Android)', precoMin: 10000, precoMax: 25000, prazo: '1-3 meses' },
      { titulo: 'Consultoria Técnica', precoMin: 150, precoMax: 150, prazo: 'Por hora' },
    ],
  },
    {
    id: 2,
    nome: 'Fernanda Lima',
    cargo: 'Designer UX/UI',
    foto: '/images/carlos-silva.jpg',
    nota: 4.8,
    totalAvaliacoes: 89,
    localizacao: 'Joinvile, SC',
    projetosConcluidos: 142,
    servicos: [
      { titulo: 'Design de App', precoMin: 2500, precoMax: 6000, prazo: '2-3 semanas' },
      { titulo: 'Redesign de Website', precoMin: 1800, precoMax: 4500, prazo: '1-2 meses' },
      { titulo: 'Consultoria de UX', precoMin: 120, precoMax: 120, prazo: 'Por hora' },
    ],
    avaliacoes: [
      { id: 1, autor: 'Rodrigo Nunes', nota: 5, comentario: 'Excelente trabalho!', data: '12/06/2026' },
      { id: 2, autor: 'Patrícia', nota: 5, comentario: 'Profissional muito atenciosa, ajustou tudo conforme pedi.', data: '28/05/2026' },
      { id: 3, autor: 'Marcelo Tavares', nota: 4, comentario: 'Ótimo trabalho, só demorou um pouco além do prazo combinado', data: '03/04/2026' },
    ],
  },
  {
    id: 3,
    nome: 'Rafael Mendes',
    cargo: 'Desenvolvedor Backend',
    foto: '/images/carlos-silva.jpg',
    nota: 4.7,
    totalAvaliacoes: 63,
    localizacao: 'Joinvile, SC',
    projetosConcluidos: 98,
    servicos: [
      { titulo: 'API REST completa', precoMin: 4000, precoMax: 12000, prazo: '3-6 semanas' },
      { titulo: 'Migração de banco de dados', precoMin: 2000, precoMax: 5000, prazo: '1-2 semanas' },
      { titulo: 'Consultoria de Arquitetura', precoMin: 180, precoMax: 180, prazo: 'Por hora' },
    ],
    avaliacoes: [
      { id: 1, autor: 'Vanessa Ribeiro', nota: 5, comentario: 'API entregue com documentação impecável, recomendo demais', data: '19/07/2026' },
      { id: 2, autor: 'Diego Santos', nota: 4, comentario: 'Bom trabalho técnico, comunicaçõa poderia ser mais rápida', data: '30/06/2026' },
      { id: 3, autor: 'Isabela Martins', nota: 5, comentario: 'Resolveu um problema de performance que ninguem mais conseguiu', data: '14/05/2026' },
    ],
  },
  {
    id: 4,
    nome: 'Juliana Costa',
    cargo: 'Especialista em Marketing Digital',
    foto: '/images/carlos-silva.jpg',
    nota: 5.0,
    totalAvaliacoes: 41,
    localizacao: 'Joinvile, SC',
    projetosConcluidos: 76,
    servicos: [
      { titulo: 'Gestão de Redes Sociais', precoMin: 1200, precoMax: 1200, prazo: 'Por mês' },
      { titulo: 'Camapanha de Google Ads', precoMin: 2000, precoMax: 5000, prazo: 'Mensal' },
      { titulo: 'Auditoria de SEO', precoMin: 800, precoMax: 800, prazo: '1 semana' },
    ],
    avaliacoes: [
      { id: 1, autor: 'André Cardoso', nota: 5, comentario: 'Minhas vendas triplicaram depois da campanha que ela montou', data: '05/08/2026' },
      { id: 2, autor: 'Beatriz Fonseca', nota: 5, comentario: 'Relatórios claros e resultados reais, super recomendo', data: '22/07/2026' },
      { id: 3, autor: 'Lucas Pereira', nota: 5, comentario: 'Melhor investimento em marketing que já fiz', data: '09/06/2026' },
]
},
{
    id: 5,
    nome: 'Bruno Almeida',
    cargo: 'Desenvolvedor Mobile (Flutter/React Native)',
    foto: '/images/carlos-silva.jpg',
    nota: 4.6,
    totalAvaliacoes: 52,
    localizacao: 'Joinvile, SC',
    projetosConcluidos: 87,
    servicos: [
      { titulo: 'App multiplataforma', precoMin: 12000, precoMax: 30000, prazo: '2-4 meses' },
      { titulo: 'Manutenção de app existente', precoMin: 100, precoMax: 100, prazo: 'Por hora' },
      { titulo: 'Publicação nas lojas', precoMin: 500, precoMax: 500, prazo: '3-5 dias' },
    ],
    avaliacoes: [
      { id: 1, autor: 'Gabriela Duarte', nota: 4, comentario: 'App funcionou bem nas duas plataformas, só teve um bug inicial', data: '11/05/2026' },
      { id: 2, autor: 'Felipe Araújo', nota: 5, comentario: 'Muito competente, entregou até antes do prazo', data: '27/06/2026' },
      { id: 3, autor: 'Renata Oliveira', nota: 4, comentario: 'Bom desenvolvedor, mas a comunicação', data: '11/05/2026' },
]
},
{
    id: 5,
    nome: 'Camila Rocha',
    cargo: 'Redatora e Copywriter',
    foto: '/images/carlos-silva.jpg',
    nota: 4.8,
    totalAvaliacoes: 110,
    localizacao: 'Joinvile, SC',
    projetosConcluidos: 203,
    servicos: [
      { titulo: 'Copy para Landing Page', precoMin: 600, precoMax: 1500, prazo: '3-5 dias' },
      { titulo: 'Conteúdo para Blog', precoMin: 250, precoMax: 250, prazo: 'Por artigo' },
      { titulo: 'Revisão de Textos', precoMin: 90, precoMax: 90, prazo: 'Por hora' },
    ],
    avaliacoes: [
      { id: 1, autor: 'Tiago Correia', nota: 5, comentario: 'Textos com ótima conversão, superou minhas expectativas.', data: '01/08/2026' },
      { id: 2, autor: 'Aline Barros', nota: 5, comentario: 'Escrita fluida e alinhada com a voz da minha marca.', data: '18/06/2026' },
      { id: 3, autor: 'Eduardo Lopes', nota: 4, comentario: 'Bom trabalho, pedi alguns ajustes mas ela atendeu rápido.', data: '22/05/2026' },
    ],
  },
{
    id: 7,
    nome: 'Thiago Barbosa',
    cargo: 'Especialista em Data Science',
    foto: '/images/carlos-silva.jpg',
    nota: 4.8,
    totalAvaliacoes: 34,
    localizacao: 'Joinvile, SC',
    projetosConcluidos: 45,
    servicos: [
      { titulo: 'Dashboard de Analytics', precoMin: 5000, precoMax: 15000, prazo: '3-5 semanas' },
      { titulo: 'Modelo de Machine Learning', precoMin: 8000, precoMax: 20000, prazo: '1-2 meses' },
      { titulo: 'Consultoria em Dados', precoMin: 200, precoMax: 200, prazo: 'Por hora' },
    ],
    avaliacoes: [
      { id: 1, autor: 'Camila Vieira', nota: 5, comentario: 'Dashboard ficou exatamente como eu precisava, muito detalhista.', data: '09/07/2026' },
      { id: 2, autor: 'Rodrigo Farias', nota: 5, comentario: 'Modelo preditivo trouxe resultados acima do esperado.', data: '25/06/2026' },
      { id: 3, autor: 'Larissa Prado', nota: 4, comentario: 'Ótimo profissional, só senti falta de mais explicações no processo.', data: '30/05/2026' },
    ],
  },
  {
    id: 8,
    nome: 'Larissa Ferreira',
    cargo: 'Ilustradora e Motion Designer',
    foto: '/images/carlos-silva.jpg',
    nota: 4.8,
    totalAvaliacoes: 58,
    localizacao: 'Joinvile, SC',
    projetosConcluidos: 91,
    servicos: [
      { titulo: 'Identidade Visual Completa', precoMin: 2000, precoMax: 5500, prazo: '2-3 semanas' },
      { titulo: 'Animação para Redes Sociais', precoMin: 800, precoMax: 2200, prazo: '1 semana' },
      { titulo: 'Ilustração Personalizada', precoMin: 400, precoMax: 400, prazo: 'Por peça' },
    ],
    avaliacoes: [
      { id: 1, autor: 'Henrique Souza', nota: 5, comentario: 'Identidade visual ficou linda, captou perfeitamente a ideia.', data: '14/08/2026' },
      { id: 2, autor: 'Natália Ramos', nota: 4, comentario: 'Animação ficou boa, mas pedi uma revisão extra.', data: '02/07/2026' },
      { id: 3, autor: 'Pedro Henrique', nota: 5, comentario: 'Trabalho rápido e com muita qualidade, super indico.', data: '19/05/2026' },
    ],
  },
  {
    id: 9,
    nome: 'Gustavo Pinheiro',
    cargo: 'Fotógrafo Profissional',
    foto: '/images/carlos-silva.jpg',
    nota: 4.8,
    totalAvaliacoes: 47,
    localizacao: 'Joinvile, SC',
    projetosConcluidos: 68,
    servicos: [
      { titulo: 'Ensaio Fotográfico Profissional', precoMin: 500, precoMax: 1500, prazo: '1 semana' },
      { titulo: 'Cobertura de Eventos', precoMin: 800, precoMax: 3000, prazo: 'A combinar' },
      { titulo: 'Edição e Tratamento de Imagens', precoMin: 50, precoMax: 50, prazo: 'Por foto' },
    ],
    avaliacoes: [
      { id: 1, autor: 'Sofia Martins', nota: 5, comentario: 'Fotos ficaram maravilhosas, superou expectativas.', data: '20/07/2026' },
      { id: 2, autor: 'Caio Ribeiro', nota: 4, comentario: 'Bom trabalho, entrega um pouco atrasada.', data: '10/06/2026' },
      { id: 3, autor: 'Débora Silveira', nota: 5, comentario: 'Muito profissional e atencioso durante o ensaio.', data: '25/05/2026' },
    ],
  },
  {
    id: 10,
    nome: 'Mariana Duarte',
    cargo: 'Tradutora e Intérprete',
    foto: '/images/carlos-silva.jpg',
    nota: 4.8,
    totalAvaliacoes: 39,
    localizacao: 'Joinvile, SC',
    projetosConcluidos: 55,
    servicos: [
      { titulo: 'Tradução de Documentos', precoMin: 150, precoMax: 600, prazo: '3-5 dias' },
      { titulo: 'Interpretação Simultânea', precoMin: 300, precoMax: 300, prazo: 'Por hora' },
      { titulo: 'Legendagem de Vídeos', precoMin: 200, precoMax: 800, prazo: '1 semana' },
    ],
    avaliacoes: [
      { id: 1, autor: 'Otávio Freitas', nota: 5, comentario: 'Tradução impecável e entregue antes do prazo.', data: '03/08/2026' },
      { id: 2, autor: 'Bianca Teixeira', nota: 5, comentario: 'Muito precisa com termos técnicos.', data: '15/06/2026' },
      { id: 3, autor: 'Rafael Costa', nota: 4, comentario: 'Bom serviço, só pedi ajustes na formatação.', data: '28/04/2026' },
    ],
  },
]